[workspace]
resolver = "2"
members = ["core/resolver", "core/udp-listener", "web/api", "web/frontend"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
