pub struct Production {
    pub id: i64,
    pub order_id: i64,
    pub bom_id: i64,
    pub day: i32,
    pub timeslot: i32,
    pub prod_line_id: i64,
}

impl Production {
    pub const TIME_SLOT_UNIT: i32 = 5;

    pub fn new(
        order_id: i64,
        bom_id: i64,
        day: i32,
        timeslot: i32,
        prod_line_id: i64,
    ) -> Production {
        Production {
            id: 0, // id is auto-generated by the database upon insertion
            order_id,
            bom_id,
            day,
            timeslot,
            prod_line_id,
        }
    }
}
